### ISSUE TITLE
How to train dreambooth with Regularization-Images

### ISSUE THREAD

**Issue by sifrah** [tobecwb/stable-diffusion-regularization-images#1]
Could you give us some examples of how to train  Regularization-Images in this repo ? 

Thanks, 
Regards

**Comment by tobecwb** [comment]
check documentation in https://github.com/ShivamShrirao/diffusers/tree/main/examples/dreambooth, especially the session about "_Training with prior-preservation loss_" (https://github.com/ShivamShrirao/diffusers/tree/main/examples/dreambooth#training-with-prior-preservation-loss)

Put the images on a directory, and specify the directory on dreambooth (on the examples, is the "CLASS_DIR")
