### ISSUE TITLE
Getting weird results

### ISSUE THREAD

**Issue by sifrah** [tobecwb/stable-diffusion-Regularization-Images#2]
I'm getting theses weird results like : 

<img width="515" alt="image" src="https://user-images.githubusercontent.com/6054235/207453909-23231d77-fd87-4e84-b654-58024d97d02b.png">

Here is my training configuration : 
```
$> accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1" \
  --pretrained_vae_name_or_path="stabilityai/sd-vae-ft-mse" \
  --output_dir="./zwx/" \
  --revision="fp16" \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --seed=1337 \
  --resolution=768 \
  --train_batch_size=1 \
  --train_text_encoder \
  --mixed_precision="fp16" \
  --use_8bit_adam \
  --gradient_accumulation_steps=1 \
  --gradient_checkpointing \
  --learning_rate=1e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=50 \
  --sample_batch_size=4 \
  --max_train_steps=1400 \
  --save_interval=500 \
  --save_sample_prompt="photo of zwx women" \
  --concepts_list="concepts_list.json"
```

Concepts list : 
```
[{
   "instance_prompt":"photo of zwx women",
   "class_prompt":"photo of a women",
   "instance_data_dir":"./zwx/",
   "class_data_dir":"./stable-diffusion-Regularization-Images/sd2.1/woman"
}]
```

Inference.py :  
```
from diffusers import StableDiffusionPipeline, DPMSolverMultistepScheduler

model_id = "./zwx/"

# Use the DPMSolverMultistepScheduler (DPM-Solver++) scheduler here instead
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt).images[0]
    
image.save("astronaut_rides_horse.png")
```

**Comment by tobecwb** [comment]
I believe it's not related to the use of these images, since I've done it a few times with success (I just can't like SD2.1).

Some issues that seem to be related to your example image:
https://github.com/TheLastBen/fast-stable-diffusion/issues/663
https://github.com/huggingface/diffusers/issues/1429

if possible, send me the images of the './zwx/' directory so that I can do local tests.

**Comment by tobecwb** [comment]
could you do a simple test?
run the same commands you did before, but don't put any files in "./stable-diffusion-Regularization-Images/sd2.1/woman" (leave the directory empty)

with that, dreambooth will generate the files (50 files) before training.

**Comment by tobecwb** [comment]
just to update.
Tried again with dreambooth from https://github.com/ShivamShrirao/diffusers and got similar results.

Running on runpod with RTX 3090, using something similar to this instructions:
https://pastebin.com/uE1WcSxD

Code:
```
export MODEL_NAME="stabilityai/stable-diffusion-2-1"
export INSTANCE_DIR="/workspace/input/"
export CLASS_DIR="/workspace/class/"
export OUTPUT_DIR="/workspace/output/"

accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --train_text_encoder \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --output_dir=$OUTPUT_DIR \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="photo of zwx woman" \
  --class_prompt="photo of a woman" \
  --resolution=768 \
  --train_batch_size=1 \
  --use_8bit_adam \
  --gradient_checkpoint \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=200 \
  --max_train_steps=1400
```

result (prompt = "a photo of zwx woman riding a horse on mars"):
![astronaut_rides_horse](https://user-images.githubusercontent.com/20520764/207721812-ccdcfb2b-fb74-43d3-8fac-2390b4d450ed.png)


same code, but with `CLASS_DIR` empty (so dreambooth generate the files):
result:
![astronaut_rides_horse2](https://user-images.githubusercontent.com/20520764/207722014-36176321-7caf-4037-8b43-524722b9c10e.png)


The problem appears to be with Dreambooth and SD2.1 (https://github.com/ShivamShrirao/diffusers/issues/162)


I tried again with Stable Diffusion 2.1 on Automatic1111 (https://github.com/AUTOMATIC1111/stable-diffusion-webui) and Dreambooth extension (https://github.com/d8ahazard/sd_dreambooth_extension/), on SD2.1 and using the images of this repository and 5 images on input (must be more to get good results).
Result:
![00012-2912554819-raw candid cinema, a photo of zwx woman riding a horse on mars, ((remarkable color)), (ultra realistic)](https://user-images.githubusercontent.com/20520764/207722537-90dd3f7b-b6d6-45f3-8b41-ca3fe03a7789.png)
