### ISSUE TITLE
pulling is failing

### ISSUE THREAD

**Issue by Petomai** [tobecwb/stable-diffusion-regularization-images#7]
I'm trying to pull the directory but git is saying it is not a git repo. 

git pull https://github.com/tobecwb/stable-diffusion-regularization-images/tree/main/sd1.5/man 

fatal: not a git repository (or any of the parent directories): .git

I'm not sure how to pull the images other than one-by-one manually.

**Comment by tobecwb** [comment]
you must use `git clone` (to clone entire repository), or download from releases page:
https://github.com/tobecwb/stable-diffusion-regularization-images/releases

the sd1.5 man is available on https://github.com/tobecwb/stable-diffusion-regularization-images/releases/tag/SD1.5

**Comment by Petomai** [comment]
Thank you. I found the releases and went to delete this before anyone saw it but you already saw it haha. ;)
